fix render error with reference not found
CruGlobal/fe pull request #137
Opened 2023-09-25 14:49 UTC by andrewroth

2023-09-25 16:56 UTC, knutsenm requested changes

2023-09-25 16:56 UTC, knutsenm commented on app/views/fe/reference_sheets/not_found.html.erb
> +<%= _("We weren't able to find a reference associated with this link. The are two common reason for this issue:") %>
```suggestion
<%= _("We weren't able to find a reference associated with this link. There are two common reasons for this issue:") %>
```

2023-09-25 17:07 UTC, knutsenm commented
I also see problems in these files:

app/views/fe/admin/panels/_prop_choice_field.html.erb:47
app/views/fe/references/edit.html.erb:1
app/views/fe/submit_pages/edit.html.erb:17

2023-09-25 17:21 UTC, knutsenm commented
And these:

app/views/fe/admin/panels/_prop_choice_field.html.erb:23 (note, different line number)
app/views/fe/admin/question_pages/_question_page.html.erb:11
app/views/fe/answer_sheets/_answer_sheet.html.erb:23
app/views/fe/questions/fe/_date_field_mmyy.html.erb:9

(found by looking for an odd number of `"` on a line)

2023-09-25 17:32 UTC, andrewroth commented
Ah, good idea! I was trying with grep to pro-actively find some, and didn't have much luck. Odd number I hadn't thought about

2023-09-25 19:51 UTC, knutsenm commented
Also,

app/views/fe/admin/panels/_prop_reference_question.html.erb:3,4
app/views/fe/reference_pages/_reference.html.erb:27

2023-09-26 14:55 UTC, knutsenm commented on app/views/fe/reference_sheets/not_found.html.erb
> +<%= _("We weren't able to find a reference associated with this link. The are two common reason for this issue:") %>
Bump

2023-09-26 14:55 UTC, knutsenm commented
> Also,
> 
> app/views/fe/admin/panels/_prop_reference_question.html.erb:3,4 app/views/fe/reference_pages/_reference.html.erb:27

Bump

2023-09-26 16:08 UTC, andrewroth commented
I think I've got them all

2023-09-26 17:43 UTC, knutsenm commented
> I think I've got them all

> > Also,
> >
> > app/views/fe/admin/panels/_prop_reference_question.html.erb:3,4
> > app/views/fe/reference_pages/_reference.html.erb:27
> Bump

Bump bump ;-)

2023-09-26 17:47 UTC, knutsenm approved these changes
🎉

2023-09-26 18:04 UTC, merged